### ISSUE TITLE
round doesn't seem to work

### ISSUE THREAD

**Issue by christianpeel** [JeffreySarnoff/ArbNumerics.jl#16]
round doesn't seem to work.   Is there an easy work-around?  Or an explanation as to why one would not want to round an ArbReal?
```
julia> H= ArbReal.([1. 2; 3 4])
2×2 Array{ArbReal{128},2}:
 1.0  2.0
 3.0  4.0

julia> round(H[1,1])
ERROR: DomainError with base (RoundingMode{:Nearest}()) not supported:
...
```
I see that I also can't calculate the `rank` of an ArbReal matrix. 

Thanks! Looks like a nice package.

**Comment by JeffreySarnoff** [comment]
ArbNumerics has very limited matrix awareness -- you can multiply them, get the determinant, get the trace, the inv, and exp(matrix).  And at least at one time you could do https://jeffreysarnoff.github.io/ArbNumerics.jl/latest/matrixfunctions/

(you may have to `using ArbNumerics, GenericLinearAlgebra, LinearAlgebra`  and maybe `GenericSVD` instead of `GenericLinearAlgebra` depending on your need)

Until GenericLinearAlgebra releases a new version .. that's it.

I have not implemented Rounding in that sense, mostly because it is not like rounding regular Floats.

Do you want to round floating point values to the (floating point) integer nearest? or something else?

**Comment by JeffreySarnoff** [comment]
see https://jeffreysarnoff.github.io/ArbNumerics.jl/latest/thetypes/ for why rounding is nontrivial

**Comment by JeffreySarnoff** [comment]
To find the `rank` you could try this (but test it first (compare with `rank(Float64.(matrix))`)
```
using ArbNumerics, GenericLinearAlgebra, LinearAlgebra

function LinearAlgebra.rank(m::Array{ArbReal{P},2}) where {P}
    arbfloatmatrix = ArbFloat{P}.(m)
    return rank(arbfloatmatrix)
end

**Comment by christianpeel** [comment]
Thanks for the details.  I didn't see anything on that page suggesting you couldn't easily round ArbFloats; is that right?  I get an error with `round(ArbFloat(1.))`

For ArbReals, my uneducated question is: why not just round the bounds and the midpoint? 

I don't have a burning need to use ArbNumerics.  I'm testing several number types with [LLLplus](https://github.com/christianpeel/LLLplus.jl); DoubleFloats work well!  If it makes sense to use ArbFloats, I'd run an example with them.

**Comment by JeffreySarnoff** [comment]
ArbFloats are sometimes ArbFloats and othertimes ArbReals looking like ArbFloats (the underlying C library does not implement many ops for ArbFloats, so there is some mirror-mirror activity going on).  Thanks for the note -- I will document it and when I think the rounding, I'll update here. [The problem with rounding the bounds and the midpoint is that you loose any assurance of containment.  There is no a priori reason to think the veridical value is near the midpoint (though it often is); it could be just alongside one of the bounds.]

**Comment by JeffreySarnoff** [comment]
Does LLLplus work as naturally with floats as with integers?

**Comment by christianpeel** [comment]
Ok, thanks for the info.  

Yes, LLLplus does work with floats and integers as the type of input matrices. Regardless of the type of input, there is a rounding step in the middle of the algorithm.

**Comment by JeffreySarnoff** [comment]
Are you always rounding to an integer?

**Comment by christianpeel** [comment]
Yes.
