### ISSUE TITLE
Eigenvalue and general eigenvalue problems

### ISSUE THREAD

**Issue by dbai1989** [JeffreySarnoff/ArbNumerics.jl#45]
Jeffrey, I am trying to use ArbNumerics.jl in my own scientific project on nuclear physics and have some questions. 

One of the key operations in my project is to solve eignvalue and general eigenvalue problems of some "singular" matrices.
Here, by "singular" I mean these matrices may appear to be singular in the usual double precision.
However, when implemented in multiple precisions, they become perfectly well-defined.

I have worked out a version of my code using the built-in BigFloat and the julia package GenericLinearAlgebra.jl.
The latter provides some functions to solve eigenvalue problems for BigFloat.

As ArbNumerics.jl has much better performance than the built-in BigFloat,
I am trying to replace BigFloat by ArbNumerics.
I am wondering if ArbNumerics has any functions to deal with eigenvalue and general eigenvalue problems.
If not, do you have any suggestion on how to deal with them within the framework of ArbNumerics?

**Comment by JeffreySarnoff** [comment]
ArbNumerics does not have internal support for that.  Have you tried using GenericLinearAlgebra.jl with ArbNumerics? 
`using LinearAlgebra, GenericLinearAlgebra, ArbNumerics` has worked with some other matrix problems.  Also try setting up your matricies using the `ArbComplex` type instead of `ArbReal` (or `ArbFloat`).  If that works, you might retry with `ArbReal` , then again with `ArbFloat` -- for problems where the result is complex, it is best to start with complex values even though their imaginary part may be zero.  Otherwise,  you could ask about other packages that solve your problem and then try using that with ArbNumerics as described.,

**Comment by dbai1989** [comment]
@JeffreySarnoff Thanks for the comments and help. I will try GenericLinearAlgebra with ArbNumerics.
